name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-26.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none

      - name: Create var dir
        run: mkdir var

      - name: Composer install
        run: composer install --no-interaction --no-progress

      - name: Composer checks
        run: |
          composer validate --no-check-lock --strict
          composer dump-autoload --dry-run --optimize --strict-psr --strict-ambiguous

      - name: Codestyle
        run: vendor/bin/php-cs-fixer fix -v --dry-run

      - name: Psalm
        run: vendor/bin/psalm --no-cache

  tests:
    name: Tests on PHP ${{ matrix.php }}
    runs-on: ubuntu-26.04
    strategy:
      fail-fast: false
      matrix:
        php: ['8.2', '8.3', '8.4', '8.5']
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Create var dir
        run: mkdir var

      - name: Composer install
        run: composer install --no-interaction --no-progress

      - name: Tests
        run: vendor/bin/phpunit
